### ISSUE TITLE
jar

### ISSUE THREAD

**Issue by NKUlpj** [DanielLin07/bookshop#1]
您好，我是一名学生，我感觉你这个项目非常好，想接着后面写，所以fork下来了，导入到idea并部署到tomcat一直是404

**Comment by DanielLin07** [comment]
不好意思哦 我现在才看到留言 部署后访问localhost:8080/home.do试试看

**Comment by lqz790192593** [comment]
class not found 👍 com.how2java.realm.DatabaseRealm .这个类是否没上传呢

**Comment by DanielLin07** [comment]
> class not found 👍 com.how2java.realm.DatabaseRealm .这个类是否没上传呢

抱歉 该项目已经很久没有维护了 找时间我会重新做的

**Comment by xiaoe2018** [comment]
hello，我也遇到了同样的问题，请问com.how2java.realm.DatabaseRealm这个类解决了吗？

**Comment by DanielLin07** [comment]
> hello，我也遇到了同样的问题，请问com.how2java.realm.DatabaseRealm这个类解决了吗？

已解决了，请pull最新代码
