### ISSUE TITLE
分词器问题

### ISSUE THREAD

**Issue by liuenci** [DanielLin07/bookshop#3]
大佬，请问这个IK分词器的jar下载不下来，估计是中央仓库里面没有这个包，请问您当时是怎么下载的呢

**Comment by DanielLin07** [comment]
抱歉 这个项目很久没有维护了 分词器可参考http://how2j.cn/k/search-engine/search-engine-analyzer/1673.html

**Comment by DanielLin07** [comment]
> 大佬，请问这个IK分词器的jar下载不下来，估计是中央仓库里面没有这个包，请问您当时是怎么下载的呢

抱歉 这个项目很久没有维护了 分词器可参考http://how2j.cn/k/search-engine/search-engine-analyzer/1673.html
